let data = [
  {
	    firstName: 'Yanze',
      lastName: 'Yu',
      title: 'Trainee',
      nationality:'Finnish',
      src:'yanze.jpg',
      alt:'',
      skills:[0],
      whySofterDeveloper:'I don’t know',
      longTermVision:`I don't know`,
      motivatesMe:'Tea',
      favoriteQuote:`I don't know`,
      joinedOn:'August 2018'
    },



  {     firstName:'Steven',
        lastName:'Nebo',
        title:'Junior Full-stack Developer',
        nationality:'Russian',
        src:'steven.jpg',
        alt:'steven yo',
        skills:['JavaScript','CSS','Photoshop','React.js','Redux', 'Node.js','MongoDB','Wordpress'],
        whySofterDeveloper:'Software is the future',
        longTermVision:'Scrum Master at one of the largest Nordic corporations',
        motivatesMe:'The desire to constantly develop myself and grow my skill set',
        favoriteQuote:'Be the change you want to see in the world',
        joinedOn:'01/08/2018'
  },
  {     firstName:'HyeSoo ',
        lastName:'Park',
        title:'trainee',
        nationality:'Korean',
        src:'hyesoo.jpg',
        alt:'hyeSoo photo',
        skills:['JavaScript','CSS','HTML5'],
        whySofterDeveloper:'It is amazing that I can build something useful and helpful for people',
        longTermVision:'',
        motivatesMe:'Willing to keep learning something new, wonderful people next to me',
        favoriteQuote:'The most beautiful things in the world cannot be seen or touched, they are       felt with the heart. To me, you will be unique in all the world.',
        joinedOn:'01.08.2018'
  },
  {     firstName:'Anuj',
        lastName:'Thapa',
        title:'Mr',
        nationality:'Nepali',
        src:'anuj.jpg',
        alt:'Anuj profile picture',
        skills:['HTML','CSS','JAVASCRIPT','C#'],
        whySofterDeveloper:'Interested in software development and a good job',
        longTermVision:'billionaire(at least millionaire)',
        motivatesMe:'Successful people',
        favoriteQuote:'Only I can change my life,No one can do it for me',
        joinedOn:'Aug.2018'
  },
  {     firstName:'Richard',
        lastName:'Jones',
        title:'Mr',
        nationality:'English',
        src:'richard.jpg',
        alt:'richard photo',
        skills:['HTML5', 'CCS', 'JavaScript', 'proofreading', 'copy editing', 'copywriting'],
        whySofterDeveloper:`It's as good a job as any`,
        longTermVision:'Acute myopia',
        motivatesMe:'Fiat currency',
        favoriteQuote:'”Beware of false knowledge; it is more dangerous than ignorance.” George Bernard Shaw',
        joinedOn:'Aug. 2018'
  },
  {     firstName:'Jolene',
        lastName:'Hoang',
        title:'Junior Developer',
        nationality:'Vietnam',
        src:'jolene.jpg',
        alt:'jolene photo',
        skills:['HTML','CSS', 'JS'],
        whySofterDeveloper:'is there something else more interesting?',
        longTermVision:'startup founder',
        motivatesMe:'waking up for a new challenge everyday',
        favoriteQuote:'when you want something all the universe conspires in helping you to achieve it',
        joinedOn:'August,2018'
  },
  {     firstName:'Biruk',
        lastName:'Yemane',
        title:'trainee',
        nationality:'Ethiopian',
        src:'biruk.jpg',
        alt:`biruk's picture`,
        skills:['HTML5','JavaScript','CSS','SQL databases','Java Basics'],
        whySofterDeveloper:'working on different projects and with different clients makes it enjoyable',
        longTermVision:`be part of 'the next start-up' to watch :)`,
        motivatesMe:'satisfaction of applying my skills to solve problems',
        favoriteQuote:'Just do it!',
        joinedOn:'1 Aug 2018'
  },
  {     firstName:'Antonija',
        lastName:'Kasum',
        title:'trainee',
        nationality:'Croatian',
        src:'antonija.jpg',
        alt:'Antonija Kasum',
        skills:['HTML', 'CSS', 'Javascript'],
        whySofterDeveloper:'Ideas come alive by the touch of your fingers',
        longTermVision:'',
        motivatesMe:`Other people's success`,
        favoriteQuote:'If you can think it you can do it!',
        joinedOn:'01.08.2018.'
  },
  {     firstName:'Elyas ',
        lastName:'Addawe',
        title:'Trainee',
        nationality:'finnish',
        src:'elyas.jpg',
        alt:'my profile picture',
        skills:['HTML','CSS', 'Javascript'],
        whySofterDeveloper:'I always wanted to create something  ',
        longTermVision:'Mix business with web developer skills',
        motivatesMe:'',
        favoriteQuote:`But it ain't how hard you hit,it's about how hard you can get hit and still keep moving forward `,
        joinedOn:'1/august/2018'
  },

  {     firstName:'yazan',
        lastName:'alhalabi',
        title:'Trainee',
        nationality:'Syria',
        src:'yazan.jpg',
        alt:'',
        skills:['JavaScript','CSS','Photoshop','Logical Thinking'],
        whySofterDeveloper:'Coding became my creative outlet and I love it for many reasons but mainly because it is a team effort and if I can think it, I can make it reality!',
        longTermVision:'Become a professional developer',
        motivatesMe:'',
        favoriteQuote:'',
        joinedOn:'1st of August'
  },
  {     firstName:'paul',
        lastName:'kiczko',
        title:'Trainee',
        nationality:'polish',
        src:'paul.jpg',
        alt:'paul photo',
        skills:['cooking', 'HTML', 'CSS', 'JavaScript', 'C/C++', 'Python', 'SQL' ],
        whySofterDeveloper:'I like the results of a successful coding session. Coding is boring sometimes, but the results are thrilling!',
        longTermVision:'The end of the world',
        motivatesMe:'coffee',
        favoriteQuote:'Need more coffee!',
        joinedOn:'1st of August 2018 AD'
  },

  {     firstName: 'Kiet',
        lastName: 'Nguyen',
        title: 'Developer',
        nationality: 'Vietnamese & Finnish',
        src: 'kiet.jpg',
        alt: 'Profile picture',
        skills:['HTML', 'CSS', 'JavaScript'],
        whySofterDeveloper: 'This is a creative job',
        longTermVision: 'Be able to develop well-known program',
        motivatesMe: 'Problem solving',
        favoriteQuote: 'A good programmer looks both ways before crossing a one-way street.',
        joinedOn: 'August 1st, 2018'
  },
  {     firstName:' Rachita',
        lastName:'Upreti',
        title:'Trainee',
        nationality:'Nepali',
        src:'rachita.jpg',
        alt:'',
        skills:['HTML','CSS','JS'],
        whySofterDeveloper:'Loving with problem , not with solution',
        longTermVision:'Developer',
        motivatesMe:'my',
        favoriteQuote:'',
        joinedOn:''
  },

  {     firstName:'Bernard',
        lastName:'Kakengi',
        title:'Software developer trainee',
        nationality:'Tanzania',
        src:'bernard.jpg',
        Alt:'bernard Image',
        skills:['HTML','CSS','JAVASCRIPT','RUBY','RUBY ON RAILS', 'SQL'],
        whySofterDeveloper:'building and designing software for people in need and able to challenge myself',
        longTermVision:'Working as a software developer and help other achieving their goals as developers',
        motivatesMe:'seeing my code running and working as required motivates me.',
        favoriteQuote:'Another coding day',
        joinedOn:'01/08/2018'
  },
  {
        firstName: 'Tata',
        lastName:'Boonamnuay',
        title:'Trainee',
        nationality:'Thailand',
        src:'tata.jpg',
        alt:'Tata Boonamnuay',
        skills:['HTML', 'CSS', 'Javascript'],
        whySofterDeveloper:'',
        longTermVision:'',
        motivatesMe:'',
        favoriteQuote:'',
        joinedOn:'08/08/2018'
   },
   {
         firstName: 'Kushal',
         lastName: 'Atreya',
         title: 'Software Developer',
         nationality: 'Nepalese',
         src: 'kushal.jpg',
         alt: 'Kushal Atreya Image',
         skills: ['HTML5', 'CSS3', 'Javascript', 'React.js', 'Redux', 'Node.js', 'Mongo DB'],
         whySofterDeveloper: `Time and again suddenly my computer wouldn't work, and then I had to use command prompt to fix it, and I started exploring more about it and loved how powerful that dark blinking rectangle was, wow now I am far from that but still exploring, now I come under the definition of software developer and yes I want to make my living out of it.`,
         longTermVision: 'To be happy of what I do and to find things that makes me happy doing',
         motivatesMe: 'The release of dopamine when the program runs',
         favoriteQuote: 'One life, Live well',
         joinedOn: '01.08.2018'
    },
        {
          firstName: 'Noman',
          lastName: 'Ashraf',
          title: 'Software Developer',
          nationality: 'Swedish Pakistani from Germany',
          src: 'noman.jpg',
          alt: 'Noman photo',
          skills: ['HTML5', 'CSS3', 'Javascript'],
          whySofterDeveloper: ``,
          longTermVision: '',
          motivatesMe: '',
          favoriteQuote: '',
          joinedOn: '01.08.2018'
        }];
