let data = [
        {
        firstName: 'Papa',
        lastName: 'Smurf',
        title: '',
        nationality: 'Smerf Land',
        src: 'papa.png',
        alt: 'papa smurf',
        skills: ['HTML5', 'CSS3', 'Javascript'],
        whySofterDeveloper: ``,
        longTermVision: '',
        motivatesMe: '',
        favoriteQuote: '',
        joinedOn: 'today'
        },
        {
        firstName: 'Smerfette',
        lastName: '',
        title: '',
        nationality: 'Smerf Land',
        src: 'smurfette.png',
        alt: 'smurfette photo',
        skills: ['HTML5', 'CSS3', 'Javascript'],
        whySofterDeveloper: ``,
        longTermVision: '',
        motivatesMe: '',
        favoriteQuote: '',
        joinedOn: 'today'
      },
        {
        firstName: 'Brainy',
        lastName: 'Smurf',
        title: '',
        nationality: 'Smerf Land',
        src: 'brainy.png',
        alt: 'brainy smurf',
        skills: ['HTML5', 'CSS3', 'Javascript'],
        whySofterDeveloper: ``,
        longTermVision: '',
        motivatesMe: '',
        favoriteQuote: '',
        joinedOn: 'today'
      },
        {
        firstName: 'Gargamel',
        lastName: '',
        title: '',
        nationality: 'The Good Guys',
        src: 'gargamel.png',
        alt: 'gargamel',
        skills: ['HTML5', 'CSS3', 'Javascript'],
        whySofterDeveloper: ``,
        longTermVision: '',
        motivatesMe: '',
        favoriteQuote: '',
        joinedOn: 'today'
      },
        {
        firstName: 'Grouchy',
        lastName: 'Smurf',
        title: '',
        nationality: 'Smerf Land',
        src: 'grouchy.png',
        alt: 'grouchy',
        skills: ['HTML5', 'CSS3', 'Javascript'],
        whySofterDeveloper: ``,
        longTermVision: '',
        motivatesMe: '',
        favoriteQuote: '',
        joinedOn: 'today'
        },
        {
        firstName: 'Hefty',
        lastName: 'Smurf',
        title: '',
        nationality: 'Smerf Land',
        src: 'hefty.png',
        alt: 'hefty',
        skills: ['HTML5', 'CSS3', 'Javascript'],
        whySofterDeveloper: ``,
        longTermVision: '',
        motivatesMe: '',
        favoriteQuote: '',
        joinedOn: 'today'
        },
        {
        firstName: 'Vanity',
        lastName: 'Smurf',
        title: '',
        nationality: 'Smerf Land',
        src: 'vanity.png',
        alt: 'vanity smurf',
        skills: ['HTML5', 'CSS3', 'Javascript'],
        whySofterDeveloper: ``,
        longTermVision: '',
        motivatesMe: '',
        favoriteQuote: '',
        joinedOn: 'today'
        },
        {
        firstName: 'Clumsy',
        lastName: 'Smurf',
        title: '',
        nationality: 'Smerf Land',
        src: 'clumsy.png',
        alt: 'clumsy smurf',
        skills: ['HTML5', 'CSS3', 'Javascript'],
        whySofterDeveloper: ``,
        longTermVision: '',
        motivatesMe: '',
        favoriteQuote: '',
        joinedOn: 'today'
        }
]
